Phase2
Star-Academy/Summer1400-SE-Team21 pull request #2
Opened 2021-07-26 10:12 UTC by nazari02105

Please check code smells and let us know if you find anything

2021-07-26 13:23 UTC, mtndaghyani commented
Hello guys
We found some Code smells in your project! Check them out. Hope it helps ;-)
1- In the FileReader class, there is an exception that is not handled in the catch block. Its a better idea to handle them or just throw them in the method signuture
2-In the InvertedIndex class, its better to rename allStuff field to allDocuments. Its more clear and precise.
3-We think that dock has a different meaning than what you have in mind! Docs may be the thing :-)
4-"list" is not a good name for a parameter. You'd better choose a more meaningful name.
5- In removeStopWords method in StringUtils class you can initialize _scanner_ in one line. Null is redundant:
`Scanner sc = new Scanner(file);`

2021-07-27 09:16 UTC, mtndaghyani approved these changes
Changes reviewed. I think now your pull request is ready to be merged!
Good luck

2021-07-27 10:35 UTC, soroushtaslimi commented
very good. I approve of the pull request.

2021-07-27 10:39 UTC, soroushtaslimi approved these changes
approved changes.

2021-07-27 12:13 UTC, mhgheisarieh requested changes

2021-07-27 12:13 UTC, mhgheisarieh commented on Phase1/src/main/java/Main.java
> +                System.out.println(docName);
> کلا تا می‌تونید تابع اصلی تون رو خلوت کنید. و خب خوبه 
مثلا این جا کلا این while و کوئری زدن رو داخل یک تابع و یک حتی آبجکت دیگه (مثلا آبجکت Search Engine) قرار بدین. که مثلا موتور جست‌وجوی ما شروع به کار کنه و شروع به کوئری زدن بکنه. 

مثلا آبچکتی به اسم    SearchEngine تعریف شه و بعدش شروع به کوئری زدن بکنه بین داک ها.

2021-07-27 12:13 UTC, mhgheisarieh commented on Phase1/src/main/java/Main.java
> +        invertedIndex.tokenizeFiles("Docs");
میشه این دو خط رو با هم تو یک خط نوشت.  تمیزتر هست

2021-07-27 12:13 UTC, mhgheisarieh commented on Phase1/src/main/java/StringUtils.java
> +            }
با Lambda expretion نمیشه زد؟

2021-07-27 12:13 UTC, mhgheisarieh commented on Phase1/src/main/java/UserInput.java
> +        }
با لامبدا نمیشه زد؟

2021-07-31 06:36 UTC, alrz1999 requested changes

2021-07-31 06:36 UTC, alrz1999 commented on Phase1/src/main/java/StringUtils.java
> +    public static void removingStopWords(TreeSet<String> theTreeSet) {
اسم توابع بهتره به صورت امری باشه و مثلا اینجا
removingStopWords
بهتره اینجوری باشه
removeStopWords

2021-07-31 06:36 UTC, alrz1999 commented on Phase1/src/main/java/InvertedIndex.java
>          FileReader fileReader = new FileReader();
بهتره به‌جای اینکه 
FileReader
رو به 
InvertedIndex
بدین؛ محتوایی که میخواین ایندکس کنین رو بدین تا اگه مثلا بعدا خواستین به جای فایل از یه جای دیگه بخونین لازم نباشه کلاس
InvertedIndex
تغییر کنه

2021-07-31 06:36 UTC, alrz1999 commented on Phase1/src/main/java/InvertedIndex.java
>              for (String allWord : allWords) {
```
for (String word : allWords) {

```

2021-07-31 06:36 UTC, alrz1999 commented on Phase1/src/main/java/SearchEngine.java
> +            TreeSet<String> containingDocs = invertedIndex.query(input);
این که 
InvertedIndex
ورودی کاربر رو پردازش کنه با
Single Responsibility
در تضاده

2021-07-31 08:22 UTC, nazari02105 commented on Phase1/src/main/java/SearchEngine.java
> +            TreeSet<String> containingDocs = invertedIndex.query(input);
موارد گفته شده همه اصلاح شد. لطفا اگر مشکلی هست بفرمایید. ممنون

2021-07-31 12:32 UTC, mhgheisarieh approved these changes
البته باز اون اینترفیس های Reader writerرو نزدین ...

2021-07-31 19:09 UTC, alrz1999 approved these changes

2021-07-31 21:21 UTC, merged