Feature/unit test
Star-Academy/Summer1400-SE-Team21 pull request #3
Opened 2021-07-31 10:23 UTC by nazari02105

لطفا تست های اضافه شده مربوط به فاز ۳ را بررسی کنید
با تشکر

2021-07-31 13:16 UTC, mtndaghyani commented on Phase1/src/test/java/InvertedIndexTest.java
> +        invertedIndex.tokenizeFiles(new FileReader().readingFiles("src/test/testDocs"));
Its better to mock the FileReader object to only test the Inverted Index class, not the others.

2021-07-31 13:27 UTC, mtndaghyani commented on Phase1/src/test/java/InvertedIndexTest.java
> +        TreeSet<String> queryResult = invertedIndex.query(new UserInput("Cause +People -pretty"));
Its better to mock the UserInput object to only test the InvertedIndex class, not the others(UserInput).

2021-07-31 13:31 UTC, mtndaghyani commented on Phase1/src/test/java/SearchEngineTest.java
> +        new SearchEngine().run();
Nothing is tested in this class! There is not assertions here.

2021-07-31 13:40 UTC, mtndaghyani commented on Phase1/src/test/java/TestClass.java
> +}
This class is redundant actually. You should move methods to their relevant classes.
For example, the first method( gettingFileAndReadIt ()) should be moved to FileReader class.

2021-07-31 13:43 UTC, mtndaghyani requested changes
Please take a look at the comments that we proposed ;-)

2021-07-31 14:06 UTC, soroushtaslimi requested changes
please view the points me and Matin stated and make changes accordingly. Thanks!

2021-08-02 06:37 UTC, mtndaghyani approved these changes

2021-08-02 06:38 UTC, soroushtaslimi approved these changes

2021-08-03 07:07 UTC, mhgheisarieh approved these changes

2021-08-05 18:12 UTC, alrz1999 approved these changes

2021-08-05 19:48 UTC, merged