Phase4
Star-Academy/Summer1400-SE-Team21 pull request #4
Opened 2021-08-03 09:35 UTC by nazari02105

سلام
لطفا فاز ۴ را بررسی بفرمایید
فقط نکته ای که لازم هست بگم این هست که ما فایل هایی که باید از آن ها اطلاعات را بخوانیم، در کنار فایل های اصلی قرار دادیم و در تنظیمات، ران رایدر را کانفیگ کردیم و 
working directory 
را تغییر دادیم پس اگر پروژه برایتان ران نشد لطفا این کار را انجام دهید

2021-08-04 07:51 UTC, mtndaghyani commented on Phase4/Project/Manager.cs
> +        }
One of the most powerful methods of Linq is Join(), which can be used to combine two lists and create a new one with specified behavior.
I just recommend that you take a look at this method. :-)

2021-08-04 07:52 UTC, mtndaghyani commented on Phase4/Project/Ranker.cs
> +        private float GetStudentScore(Student student)
I think it's better to rename this method to _GetStudentAverage_.

2021-08-04 07:58 UTC, mtndaghyani commented on Phase4/Project/Ranker.cs
> +            return rankedStudent;
_rankedStudent_ is actually redundant and not used for any computation. Therefore its a better idea to remove that and just return the right hand side of the assignment.

2021-08-04 08:00 UTC, mtndaghyani requested changes
چند مورد جزئی کامنت شدن لطفا بررسی و در صورت نیاز اصلاح کنید.
(ببخشید بابت انگلیسی نوشتن چون نمیشه فارسی و انگلیسی رو با هم نوشت:-)

2021-08-05 19:32 UTC, alrz1999 approved these changes

2021-08-05 19:32 UTC, alrz1999 commented on Phase4/Project/Manager.cs
> +                Console.WriteLine(student.FirstName + " " + student.LastName + " " + student.Average);
اینو می‌تونستین تو
override ToString
کلاس
student 
بزارین

2021-08-05 19:32 UTC, alrz1999 commented on Phase4/Project/Ranker.cs
> +            CalculateAverages();
https://softwareengineering.stackexchange.com/questions/208828/passing-an-object-into-a-method-which-changes-the-object-is-it-a-common-anti

2021-08-06 12:24 UTC, mtndaghyani approved these changes

2021-08-07 08:25 UTC, soroushtaslimi approved these changes
Everything looks great.

2021-08-07 09:44 UTC, mhgheisarieh approved these changes

2021-08-07 09:48 UTC, merged