Phase5
Star-Academy/Summer1400-SE-Team21 pull request #5
Opened 2021-08-05 19:58 UTC by nazari02105

سلام لطفا فاز ۵ را بررسی بفرمایید

2021-08-07 08:23 UTC, soroushtaslimi commented on Phase5/SearchEngine/TestProject1/InvertedIndexTest.cs
> +            InvertedIndex invertedIndex = (InvertedIndex)new InvertedIndex().TokenizeFiles(fileReader.ReadingFiles(Path));
these test method names do not show the case which is under test. It is better to rename them to a more meaningful name.

2021-08-07 08:24 UTC, soroushtaslimi requested changes
please take a look at the comments.

2021-08-09 10:24 UTC, alrz1999 requested changes

2021-08-09 10:24 UTC, alrz1999 commented on Phase5/SearchEngine/SearchEngine/FileReader.cs
> +            catch (Exception e)
الان اینجا اوکیه ولی کلا هر جا اکسپشن داشتین یا دوباره خودشو 
throw
کنین یا 
exception message
ش رو پرینت کنین.
اینجا مثلا ممکنه یه فایل یه جای دیگه باز باشه ولی شما خطا میدین 
Path
اشتباه بوده

2021-08-09 10:24 UTC, alrz1999 commented on Phase5/SearchEngine/SearchEngine/InvertedIndex.cs
> +            allDocuments.ToList().ForEach(pair => StringUtils.ProcessRawTokens(Tokenize(pair.Value)).ToList().ForEach(
به نظرم این 
ForEach
دومیه رو یه 
for
بزنین از نظر خوانایی بهتره

2021-08-09 10:24 UTC, alrz1999 commented on Phase5/SearchEngine/SearchEngine/SearchEngine.cs
> +                if (containingDocs.Count==0)
https://stackoverflow.com/questions/2125066/is-it-a-bad-practice-to-use-an-if-statement-without-curly-braces

2021-08-10 06:20 UTC, mtndaghyani approved these changes

2021-08-10 06:20 UTC, soroushtaslimi approved these changes

2021-08-10 14:44 UTC, mhgheisarieh approved these changes
عالی.

یکی دو تا مورد اکپشن ها بود که علیرضا گفته بود.

2021-08-12 18:57 UTC, alrz1999 approved these changes

2021-08-13 04:39 UTC, merged